.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 13/02/2014               \" DATE 
.Dt shrinkwrap 1             \" Program name and manual section number 
.Os Darwin
.Sh NAME                     \" Section Header - required - don't modify 
.Nm shrinkwrap
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Ar pngfile              \"
.Ar xmlfile              \"
.Ar outputfile           \"
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
is a tool for triangulating bitmap alpha.
.Pp                      \" Inserts a space
.Sh OPTIONS
.Bl -tag -width -indent\" Begins a tagged list 
.It pngfile               \" Each item preceded by .It macro
Input png bitmap
.It xmlfile
Input xml file describing sprite locations and dimensions
.It outputfile
Output binary file
.El                      \" Ends the list
.Pp
.\" .Sh DIAGNOSTICS       \" May not be needed
.\" .Bl -diag
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .El
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
